name: chatbot_release_issue

on:
  issue_comment:
    types: [created, edited]

jobs:
  chatbot_release_issue:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ toJson(github.event) }}