name: create_hotfix

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'バージョン'
        required: true
        default: 'x.x.x'

jobs:
  create_hotfix:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Create hotfix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "bot"
          git config --local user.email bot@example.com
          python3 .github/workflows/create_hotfix.py ${{github.event.inputs.version}}
